### ISSUE TITLE
Table rows should be clickable

### ISSUE THREAD

**Issue by romaintailhurat** [Making-Sense-Info/Addict#1]
It makes browsing easier.

**Comment by NicoLaval** [comment]
Sure about that?

For instance it's more complicated to select and copy elements

**Comment by romaintailhurat** [comment]
We could have copy button

**Comment by romaintailhurat** [comment]
From my point of view, clicking on the element to get details is the most regular thing you would do, so it should be the easiest. Copy is  secondary, so it should be second to usability.

**Comment by romaintailhurat** [comment]
Done in `0.4.1`
